### ISSUE TITLE
Unrecognized Receiver

### ISSUE THREAD

**Issue by bonedaddy** [dragino/rpi-lora-tranceiver#5]
I just received the rpi lora/gps hat and connected it to my Raspberry Pi 3B+,  on running the `dragino_lora_app`  code, and get the following error

```
$ ./dragino_lora_app sender hello
Unrecognized transceiver.
```

# System Info

Model: Raspberry Pi 3B+
```
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```

```
Linux rpi3 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by bonedaddy** [comment]
was able to solve this issue but am having troubles with the BCM pinouts on the RPI 3 (https://github.com/stianeikeland/go-rpio/issues/54) + https://github.com/dragino/rpi-lora-tranceiver/issues/6

**Comment by theRosyProject** [comment]
Dear bone daddy, I have the same problem with a raspberry pi 3b+ paired with the Dragino LoRa GPS hat v1.4. When the program is launched a packet is transmitted through LoRa, but after this first communication is no longer possible to send data and I have to shutdown and remove the power to the pi. Since the Lora-Rx blue LED stays on with a steady light after the first run, do you think this could be the issue?

```
$ ./dragino_lora_app sender HI
SX1276 detected, starting.
Send packets at SF7 on 868.100000 Mhz.
------------------
send: HI
```
```
$ ./dragino_lora_app sender HI
Unrecognized transceiver.
```

How do you solve your problem!? Thank you!
Fede
